### ISSUE TITLE
MixedTimePicker中onTimeSelect返回的Date只有时分改变了

### ISSUE THREAD

**Issue by ikarosi** [jaaksi/pickerview#1]
您好，我下载了您的demo，使用MixedTimePicker中发现滚动后Date里返回时间只有时和分改变了，年月日没有改变。

**Comment by jaaksi** [comment]
非常感谢您的反馈，最新的代码已经修复该问题。请使用最新版本 1.0.1

**Comment by yuger** [comment]
@jaaksi 可不可以做成像抖音/火山小视频那样左上、右上角圆角的效果？

**Comment by yuger** [comment]
@jaaksi 抖音评论是一个从下向上的弹窗，有两个圆角

**Comment by jaaksi** [comment]
这个啊，简单，你自定义一个titlebar，搞个圆角的背景就可以了。
