### ISSUE TITLE
应用API及例子介绍看着杂乱无章

### ISSUE THREAD

**Issue by LaughingGeek** [jaaksi/pickerview#13]
API介绍及例子不能一眼看出如何使用，没有流程说明，比如按照导入库，xml文件，基础的类使用，给出的代码都是没头没尾的，看着很糟心，虽然库不错，但文档很差劲

**Comment by jaaksi** [comment]
谢谢你这么优秀的点评

**Comment by LaughingGeek** [comment]
一眼真的不太好看啊！不过我还是看了，花了一个多小时用的很顺畅，库很不错，API真的可以写的简单点，比如以一个完整的例子为流程
