### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by Suguiqiang** [jaaksi/pickerview#14]
可以考虑适配androidX和增加bottomBar？

**Comment by xreleven** [comment]
大佬 2.0.0 版本 不支持联动如何设置

**Comment by jaaksi** [comment]
@Suguiqiang androidX后续考虑适配。增加bottomBar是什么需求背景？
@xreleven OptionPicker的setData方法参数是个可变长数组，如果你传入多个数据源，就是不关联的。一个数据源就是关联的。
