### ISSUE TITLE
点击无法返回相对应的信息，只能滑动选择

### ISSUE THREAD

**Issue by YUHAN-GUO** [jaaksi/pickerview#19]
滑动选择 点击确定前
![1563345952(1)](https://user-images.githubusercontent.com/43516357/61353256-e8c5f800-a8a1-11e9-9dc1-d78005905c01.png)
滑动选择 点击确定后
![Uploading 1563346158(1).png…]()
点击选择 点击确定前
![1563346219(1)](https://user-images.githubusercontent.com/43516357/61353368-38a4bf00-a8a2-11e9-9600-0e3e78ce863e.png)
点击选择 点击确定后
![1563346279(1)](https://user-images.githubusercontent.com/43516357/61353413-5b36d800-a8a2-11e9-9481-e2dfe1407b03.png)
点击选择无法得到相对应的值

**Comment by jaaksi** [comment]
是的，并不支持。

**Comment by jaaksi** [comment]
是的，并不支持。
