### ISSUE TITLE
Bug: 选中单条数据 点击确定按钮 无效

### ISSUE THREAD

**Issue by xiaxiayige** [jaaksi/pickerview#22]
调试版本：3.0.0

操作步骤1 ：

     点击一个条目，然后点击右上角确定按钮

结果 1 ：

    点击确定以后无反应。
----------------------------------------------------------------------

操作步骤2：
       
    通过滑动选中一个条目，点击确定按钮

结果 2：

     点击确定正常回调

断点类：DefaultPickerDialog  

断点方法：

`@CallSuper
  @Override
  public void onClick(View v) {
    if (!picker.canSelected()) return;//  滑动未停止不响应点击事件    这行代码有问题。
    if (v == getBtnConfirm()) {
      // 给用户拦截
      if (mOnPickerChooseListener == null || mOnPickerChooseListener.onConfirm()) {
        // 抛给picker去处理
        dismiss();
        picker.onConfirm();
      }
    } else if (v == getBtnCancel()) {
      dismiss();
      if (mOnPickerChooseListener != null) {
        mOnPickerChooseListener.onCancel();
      }
    }
  }`

**Comment by DeAikon** [comment]
@jaaksi 
Thk u for made this great widget, any plan to fix this issue? 
感谢你做了这个很棒的控件，有修复这个issue的计划吗？

**Comment by jaaksi** [comment]
@xiaxiayige @DeAikon bug于3.0.1版本已经修复。感谢反馈。

**Comment by DeAikon** [comment]
@jaaksi So Great ,  Thk U !

**Comment by ppg408331701** [comment]
我正好遇到这个问题，目前文档显示最新版本是3.0.0.希望作者能修改一下文档到3.0.1
