### ISSUE TITLE
时间选择器可以自定义数据adapter吗？

### ISSUE THREAD

**Issue by zhangsange** [jaaksi/pickerview#25]
**作者好，很感谢提供这么好的库。**
现在有个需求是年月日正常选择；小时跟分钟，用户可能当时不确定，所以会在正常的时间后加个未知的选项。
如
hour:00,01,02......23,未知；

minute:01,02,03,04,......59,60,未知。

最后的选择结果可以是

- 2020-02-02 18:58，

- 2020-02-02 18:未知，

- 2020-02-02 未知:未知，

- 2020-02-02 未知:58。

再次打开的时候，也可以数据回显，自动选择之前选择的时间日期。
不知道现有api是否能满足上面的需求。
期待回复

**Comment by jaaksi** [comment]
目前的api无法满足你的需求，这种需求还是比较独特的，可以参考代码，自己定义Picker来实现。
