### ISSUE TITLE
请问取消与确定按钮的文本更改可以开放一下吗

### ISSUE THREAD

**Issue by causeday** [jaaksi/pickerview#30]
如题，想把确认和取消按钮的文本更改一下（改成英文），找了半天发现在default picker dialog里改不了……
谢谢，这个picker view很好用！

**Comment by jaaksi** [comment]
如果是3.x的版本，调用DefaultPickerDialog的getBtnConfirm()方法，然后强转为TextView，然后设置即可，也可以自定义一个Dialog。2.x版本的调用ITopBar的方法拿到TextView即可

**Comment by jaaksi** [comment]
> 如题，想把确认和取消按钮的文本更改一下（改成英文），找了半天发现在default picker dialog里改不了……
> 谢谢，这个picker view很好用！

如果是3.x的版本，调用DefaultPickerDialog的getBtnConfirm()方法，然后强转为TextView，然后设置即可，也可以自定义一个Dialog。2.x版本的调用ITopBar的方法拿到TextView即可
