### ISSUE TITLE
能都开放getSelectedDates() 方法

### ISSUE THREAD

**Issue by JetQiao** [jaaksi/pickerview#41]
![image](https://user-images.githubusercontent.com/3361048/188054199-3419d655-57db-4759-bbd4-18cdbf00eda4.png)

在非dialog的情况下，需要获取选择的时间，能否开放这个方法

**Comment by jaaksi** [comment]
最新版本已解决，在非Dialog情况下不回调问题

**Comment by jaaksi** [comment]
> ![image](https://user-images.githubusercontent.com/3361048/188054199-3419d655-57db-4759-bbd4-18cdbf00eda4.png)
> 
> 在非dialog的情况下，需要获取选择的时间，能否开放这个方法

最新版本已解决，在非Dialog情况下不回调问题
