### ISSUE TITLE
惯性滑动如果刚好某个Item到中间，此时按确定select还是原来的

### ISSUE THREAD

**Issue by healthyxth** [jaaksi/pickerview#9]

**Comment by healthyxth** [comment]
if (mIsFling) {
        mIsFling = false;
        moveToCenter(); // 滚动到中间位置
      } else if (mIsMovingCenter) { // 选择完成，回调给监听器

进入moveToCenter，但是mMoveLength为0，直接return出去了，所有没有把select的变动回调出去

**Comment by jaaksi** [comment]
2.0.0版本试一下
